In [1]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [3]:
df = pd.read_csv('homeprices_multivariate.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [5]:
df.bedrooms.median()

np.float64(4.0)

In [6]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price', axis='columns'), df.price)

LinearRegression()

In [8]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [9]:
reg.intercept_

np.float64(221323.0018654043)

#### home with 3000 sqr ft area, 3 bedrooms, 40 year old

In [10]:
reg.predict([[3000,3,40]])

C:\Users\aksha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [11]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.0018654043

498408.2515740243

#### price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [12]:
reg.predict([[2500,4,5]])

C:\Users\aksha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

# Hiring Model

In [13]:
df_hire = pd.read_csv('hiring.csv')
df_hire

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [14]:
df_hire.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [15]:
from word2number import w2n

In [16]:
df_hire.experience = df_hire.experience.fillna('zero')

In [17]:
df_hire.experience = df_hire.experience.apply(w2n.word_to_num)

In [18]:
median_test_score = df_hire['test_score(out of 10)'].mean()

In [19]:
import math
median_test_score = math.floor(median_test_score)
median_test_score

7

In [20]:
df_hire['test_score(out of 10)'] = df_hire['test_score(out of 10)'].fillna(median_test_score)

In [21]:
df_hire.experience = df_hire.experience.replace(0, np.nan)

In [22]:
df_hire.experience = df_hire.experience.fillna(df_hire.experience.median())

In [23]:
hire_reg = linear_model.LinearRegression()
hire_reg.fit(df_hire.drop('salary($)',axis='columns'),df_hire['salary($)'])

LinearRegression()

In [24]:
hire_reg.predict([[2,9,6]])

C:\Users\aksha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([46799.52198459])

In [25]:

hire_reg.predict([[12,10,10]])

C:\Users\aksha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([88536.36625871])

In [26]:
hire_reg.coef_

array([2874.43853793, 1225.36778341, 2941.77277785])

In [27]:
hire_reg.intercept_

np.float64(12371.698190958909)